module.exports = {
  apps: [
    {
      name: 'petqas-api',
      script: '.venv/bin/uvicorn',
      args: 'src.main:app --host 0.0.0.0 --port 3003 --workers 2 --access-log',
      cwd: '/var/www/petqas/apps/api',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      env: {
        APP_ENV: 'production',
      },
      max_memory_restart: '500M',
      kill_timeout: 15000,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 4000,
      error_file: '/var/www/petqas/logs/api-error.log',
      out_file: '/var/www/petqas/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      watch: false,
    },
    {
      name: 'petqas-web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3004',
      cwd: '/var/www/petqas/apps/web',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      max_memory_restart: '500M',
      kill_timeout: 5000,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: '/var/www/petqas/logs/web-error.log',
      out_file: '/var/www/petqas/logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      watch: false,
    },
    {
      name: 'petqas-celery-worker',
      script: '.venv/bin/celery',
      args: '-A src.celery_app worker --loglevel=info -Q default,outbox,notifications --concurrency=2',
      cwd: '/var/www/petqas/apps/api',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      error_file: '/var/www/petqas/logs/celery-worker-error.log',
      out_file: '/var/www/petqas/logs/celery-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      watch: false,
    },
    {
      name: 'petqas-celery-beat',
      script: '.venv/bin/celery',
      args: '-A src.celery_app beat --loglevel=info',
      cwd: '/var/www/petqas/apps/api',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 5,
      restart_delay: 10000,
      error_file: '/var/www/petqas/logs/celery-beat-error.log',
      out_file: '/var/www/petqas/logs/celery-beat-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      watch: false,
    }
  ]
};
