# ============================================
# Grafana Tempo - Distributed Tracing Backend
# ============================================
# Dokumantasyon: https://grafana.com/docs/tempo/latest/configuration/

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 168h          # 7 gun trace saklama (SLA 7-gun penceresi icin)

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: emlak-dev
  storage:
    path: /var/tempo/generator/wal
